site_name: Coisas Que Não Ensinam em TI
repo_url: https://github.com/moreirayokoyama/coisas-que-nao-ensinam-em-ti
repo_name: moreirayokoyama/coisas-que-nao-ensinam-em-ti

nav:
  - "Coisas Que Não Ensinam em TI": index.md
  - Aulas:
    - "Aula 1 - O Shell":
      - aulas/01-shell/index.md
      - aulas/01-shell/01-o-que-e.md
      - aulas/01-shell/02-bash.md
      - aulas/01-shell/03-navegando.md
      - aulas/01-shell/04-permissoes.md
      - aulas/01-shell/05-manipulando-arquivos.md
      - aulas/01-shell/06-caminho-absoluto-relativo.md
      - aulas/01-shell/07-conectando-programas.md
      - aulas/01-shell/08-comandos-uteis.md
      - aulas/01-shell/09-conclusao.md
    - "Aula 2 - Introdução a Criação Scripts com Bash":
      - aulas/02-scripting/index.md
      - aulas/02-scripting/01-hello-world.md
      - aulas/02-scripting/02-expressoes-expansoes.md
      - aulas/02-scripting/03-variaveis.md
      - aulas/02-scripting/04-composicao-de-comandos.md
      - aulas/02-scripting/05-expansoes-de-chave.md
      - aulas/02-scripting/06-stream-de-erro.md
      - aulas/02-scripting/07-scripts.md
      - aulas/02-scripting/08-conclusao.md
    - "Aula 3 - Explorando o Editor de Textos (Visual Studio Code)":
      - aulas/03-text-editors/index.md
      - aulas/03-text-editors/00-instalando-vscode.md
      - aulas/03-text-editors/01-explorando-a-interface.md
      - aulas/03-text-editors/02-editor-de-arquivos.md
      - aulas/03-text-editors/03-extensoes.md
      - aulas/03-text-editors/04-trabalhando-com-codigo.md
      - aulas/03-text-editors/05-trabalhando-com-diretorios.md
      - aulas/03-text-editors/06-workspaces.md
      - aulas/03-text-editors/07-terminal.md
      - aulas/03-text-editors/08-conclusao.md
    - "Aula 4 - Sistema de Controle de Versionamento de Código - Git":
      - aulas/04-source-control/index.md
      - aulas/04-source-control/01-instalando-git.md
      - aulas/04-source-control/02-iniciando-um-repo.md
      - aulas/04-source-control/03-como-git-acompanha-repo.md
      - aulas/04-source-control/04-viajando-no-tempo.md
      - aulas/04-source-control/05-modificacoes-complexas.md
      - aulas/04-source-control/06-git-diff.md
      - aulas/04-source-control/07-branches.md
      - aulas/04-source-control/cap_08.md
      - aulas/04-source-control/cap_09.md
      - aulas/04-source-control/cap_10.md
      - aulas/04-source-control/cap_11.md
      - aulas/04-source-control/cap_12.md
      - aulas/04-source-control/cap_13.md

theme:
  name: material
  language: pt-BR
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share
    - content.footnote.tooltips
    - navigation.indexes
    - navigation.sections
  palette:
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Modo noturno

markdown_extensions:
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.keys
  - footnotes
  - admonition
  - markdown.extensions.attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

plugins:
  - macros
  - glightbox
  - mkdocs-video
  - search:
      lang: pt
  - git-authors:
      show_email_address: false
      show_line_count: true
  - git-revision-date-localized
  - social
  - with-pdf:
      author: Daniel Yokoyama
      cover_title: Coisas Que Não Ensinam Em TI
      cover_subtitle: Adaptação para o Português do curso "The Missing Semester in Your CS Formation" do MIT
      copyright: CC BY-NC-SA
      toc_level: 6
      enabled_if_env: ENABLE_PDF_EXPORT
      toc_title: Índice
  - exclude:
      glob:
        - "wip.md"
        - "*-__remove__.*"
  - exclude-unused-files
  - mkdocs_quiz

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/codandocomotio
    - icon: fontawesome/brands/github
      link: https://github.com/moreirayokoyama
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@CodandoComOTio

#hooks:
#  - hooks/quiz_hook.py
