[tool.poetry]
name = "coisas-que-nao-ensinam-em-ti"
version = "0.1.0"
description = ""
authors = ["Tio Dani <792153+moreirayokoyama@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "coisas-que-nao-ensinam-em-ti"}]

[tool.poetry.dependencies]
python = "^3.12"
mkdocs = "^1.6.0"
mkdocs-material = "^9.5.29"
taskipy = "^1.13.0"
mkdocs-glightbox = "^0.4.0"
mkdocs-video = "^1.5.0"
mkdocs-git-authors-plugin = "^0.9.0"
mkdocs-git-revision-date-localized-plugin = "^1.2.6"
pillow = "^10.4.0"
cairosvg = "^2.7.1"
mkdocs-with-pdf = "^0.9.3"
mkdocs-exclude = "^1.0.2"
mkdocs-exclude-unused-files = "^1.4.0"
mkdocs-macros-plugin = "^1.0.5"
invoke = "^2.2.0"
rich = "^13.7.1"
typos = "^1.23.2"
ruff = "^0.5.2"
mkdocs-quiz = "^0.0.41"

[tool.poetry.group.snippets.dependencies]
pytest = "^8.1.1"

[tool.taskipy.tasks]
serve = {cmd="mkdocs serve --dev-addr localhost:8080", help="Executa o servidor local do mkdocs"}
deploy = {cmd="mkdocs gh-deploy", help="Faz o deploy da página em produção"}
slides = {cmd="marp -I slides/brutos/ --html --theme slides/brutos/rose-pine.css --allow-local-files --pdf -o slides/pdf/", help="Gera os slides em pdf"}
slides_html = {cmd="marp -I slides/brutos --html --theme slides/brutos/rose-pine.css --allow-local-files -o slides/html", help="Gera os slides em html (formato usado nas aulas)"}
pdf = {cmd="ENABLE_PDF_EXPORT=1 mkdocs build", help="Cria um pdf único de todo o curso (não otimizado ainda)"}
ruff = 'ruff check'

[tool.ruff]
line-length = 79

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']
ignore = ['E402', 'F811']

[tool.ruff.format]
preview = true
quote-style = 'single'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"